variable "env" {}
variable "type" {}
variable "vpc_id" {}
variable "sg_cidrs" {}
variable "tags" {}
variable "component" {}
variable "internal" {}
variable "subnets" {}
variable "enable_https" {}
variable "target_group_arn" {}
variable "certificate_arn" {}